site_name: Dropt

pages:
- Introduction: index.md
- ChangeLog: changelog.md
- Getting Started:
  - Getting Started: gettingstarted.md
  - Configuration Files: configuration.md
  - Commands: commands.md
  - Debugging: debugging.md
  - Block Strings: blockstrings.md
- Examples:
  - Basic Replacement: examples/basic_replacement.md
  - Selective Removal: examples/selective_removal.md
  - Grass Drops: examples/grass_drops.md
  - Leaf Drops: examples/leaf_drops.md
  - Tool Restriction: examples/tool_restriction.md
  - Advanced Fortune: examples/advanced_fortune.md
  - Silk Touch: examples/silk_touch.md
  - Match Quantity: examples/match_quantity.md
  - Distance From Spawn: examples/distance.md
  - NBT: examples/nbt.md
  - GameStages: examples/gamestages.md
  - Forced Drops: examples/forced_drops.md
  - Drop All: examples/drop_all.md
  - BlockState Replacement: examples/blockstate_replacement.md
  - Fallthrough: examples/fallthrough.md
- ZenScript:
  - Dropt: zs/dropt.md
  - RuleList: zs/rulelist.md
  - Rule: zs/rule.md
  - Harvester: zs/harvester.md
  - Drop: zs/drop.md
  - Examples: zs/example.md
- JSON:
  - Syntax: json/syntax.md
  - Examples: json/examples.md
- API:
  - Reference: api/reference.md
- Development:
  - Contributor's License Agreement: cla.md

theme: readthedocs

markdown_extensions:
- admonition
- attr_list

extra_css: [custom.css]